"""Initial schema

Revision ID: 9564efc4f1dc
Revises: 
Create Date: 2026-01-07 12:43:48.045581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9564efc4f1dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('northbound_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_northbound_instances')),
    sa.UniqueConstraint('endpoint_path', name=op.f('uq_northbound_instances_endpoint_path'))
    )
    op.create_index(op.f('ix_northbound_instances_name'), 'northbound_instances', ['name'], unique=True)
    op.create_table('onboarded_servers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport_type', sa.Enum('STDIO', 'STREAMABLE_HTTP', 'SSE', name='transporttype'), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'RECONNECTING', name='serverstatus'), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarded_servers'))
    )
    op.create_index(op.f('ix_onboarded_servers_name'), 'onboarded_servers', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('instance_tags',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['northbound_instances.id'], name=op.f('fk_instance_tags_instance_id_northbound_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_instance_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instance_id', 'tag_id', name=op.f('pk_instance_tags'))
    )
    op.create_table('tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('source_server_id', sa.String(length=36), nullable=False),
    sa.Column('source_server_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_server_id'], ['onboarded_servers.id'], name=op.f('fk_tools_source_server_id_onboarded_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools'))
    )
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_table('instance_tools',
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['northbound_instances.id'], name=op.f('fk_instance_tools_instance_id_northbound_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_instance_tools_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instance_id', 'tool_id', name=op.f('pk_instance_tools'))
    )
    op.create_table('tool_tags',
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tool_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_tags_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'tag_id', name=op.f('pk_tool_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_tags')
    op.drop_table('instance_tools')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_table('tools')
    op.drop_table('instance_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_onboarded_servers_name'), table_name='onboarded_servers')
    op.drop_table('onboarded_servers')
    op.drop_index(op.f('ix_northbound_instances_name'), table_name='northbound_instances')
    op.drop_table('northbound_instances')
    # ### end Alembic commands ###
